---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow: 
    collect:
      metrics:
        /intel/procfs/meminfo/active: {}							 
        /intel/procfs/meminfo/active_file: {}
        /intel/procfs/meminfo/buffers: {}
        /intel/procfs/meminfo/buffers_perc: {}
        /intel/procfs/meminfo/cached: {}
        /intel/procfs/meminfo/cached_perc: {}
        /intel/procfs/meminfo/cma_free: {}
        /intel/procfs/meminfo/cma_free_perc: {}
        /intel/procfs/meminfo/cma_total: {}
        /intel/procfs/meminfo/cma_total_perc: {}
        /intel/procfs/meminfo/hardware_corrupted: {}
        /intel/procfs/meminfo/hardware_corrupted_perc: {}
        /intel/procfs/meminfo/high_free: {}
        /intel/procfs/meminfo/high_free_perc: {}
        /intel/procfs/meminfo/high_total: {}		
        /intel/procfs/meminfo/high_total_perc: {}					
        /intel/procfs/meminfo/huge_pages_free: {}						 
        /intel/procfs/meminfo/huge_pages_free_perc: {}			 
        /intel/procfs/meminfo/huge_pages_rsvd: {} 						 
        /intel/procfs/meminfo/huge_pages_rsvd_perc: {}					
        /intel/procfs/meminfo/huge_pages_surp: {}				 
        /intel/procfs/meminfo/huge_pages_surp_perc: {}			 		 
        /intel/procfs/meminfo/kernel_stack: {}					 
        /intel/procfs/meminfo/kernel_stack_perc: {} 					 
        /intel/procfs/meminfo/low_free: {} 							 
        /intel/procfs/meminfo/low_free_perc: {}						 
        /intel/procfs/meminfo/low_total: {}						 
        /intel/procfs/meminfo/low_total_perc: {}				 			 
        /intel/procfs/meminfo/mem_available: {}						 
        /intel/procfs/meminfo/mem_available_perc: {}		 
        /intel/procfs/meminfo/mem_free: {}						 
        /intel/procfs/meminfo/mem_free_perc: {}					 
        /intel/procfs/meminfo/mem_total: {}						 
        /intel/procfs/meminfo/mem_total_perc: {}				
        /intel/procfs/meminfo/mem_used: {}					 
        /intel/procfs/meminfo/mem_used_perc: {}					 
        /intel/procfs/meminfo/mlocked: {}						
        /intel/procfs/meminfo/mlocked_perc: {}				 
        /intel/procfs/meminfo/mmap_copy: {}						 
        /intel/procfs/meminfo/mmap_copy_perc: {}					 
        /intel/procfs/meminfo/nfs_unstable: {}				 
        /intel/procfs/meminfo/nfs_unstable_perc: {}			 					 
        /intel/procfs/meminfo/swap_free: {}						 
        /intel/procfs/meminfo/swap_free_perc: {}					 
        /intel/procfs/meminfo/swap_total: {}					 
        /intel/procfs/meminfo/swap_total_perc: {}				 
        /intel/procfs/meminfo/unevictable: {}					 
        /intel/procfs/meminfo/unevictable_perc: {}					 
        /intel/procfs/meminfo/vmalloc_chunk: {}
        /intel/procfs/meminfo/vmalloc_chunk_perc: {}
        /intel/procfs/meminfo/vmalloc_total: {}
        /intel/procfs/meminfo/vmalloc_total_perc: {}
        /intel/procfs/meminfo/vmalloc_used: {}
        /intel/procfs/meminfo/vmalloc_used_perc: {}
        /intel/procfs/meminfo/writeback: {}
        /intel/procfs/meminfo/writeback_perc: {}
      publish:
        -
          plugin_name: "influxdb"
          config:
            host: "influxdb"
            port: 8086
            database: "k8s"
            user: "admin"
            password: "admin"
    